# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/andrei/Downloads/clion-2020.2.4/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/andrei/Downloads/clion-2020.2.4/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = tdp005-projekt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = tdp005-projekt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/andrei/Downloads/clion-2020.2.4/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/andrei/Downloads/clion-2020.2.4/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andrei/school/tdp005/GAME/tdp005-projekt/CMakeFiles /home/andrei/school/tdp005/GAME/tdp005-projekt/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andrei/school/tdp005/GAME/tdp005-projekt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/build
.PHONY : game/fast

Ant.o: Ant.cpp.o

.PHONY : Ant.o

# target to build an object file
Ant.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Ant.cpp.o
.PHONY : Ant.cpp.o

Ant.i: Ant.cpp.i

.PHONY : Ant.i

# target to preprocess a source file
Ant.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Ant.cpp.i
.PHONY : Ant.cpp.i

Ant.s: Ant.cpp.s

.PHONY : Ant.s

# target to generate assembly for a file
Ant.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Ant.cpp.s
.PHONY : Ant.cpp.s

AntSwarm.o: AntSwarm.cpp.o

.PHONY : AntSwarm.o

# target to build an object file
AntSwarm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/AntSwarm.cpp.o
.PHONY : AntSwarm.cpp.o

AntSwarm.i: AntSwarm.cpp.i

.PHONY : AntSwarm.i

# target to preprocess a source file
AntSwarm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/AntSwarm.cpp.i
.PHONY : AntSwarm.cpp.i

AntSwarm.s: AntSwarm.cpp.s

.PHONY : AntSwarm.s

# target to generate assembly for a file
AntSwarm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/AntSwarm.cpp.s
.PHONY : AntSwarm.cpp.s

Character.o: Character.cpp.o

.PHONY : Character.o

# target to build an object file
Character.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Character.cpp.o
.PHONY : Character.cpp.o

Character.i: Character.cpp.i

.PHONY : Character.i

# target to preprocess a source file
Character.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Character.cpp.i
.PHONY : Character.cpp.i

Character.s: Character.cpp.s

.PHONY : Character.s

# target to generate assembly for a file
Character.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Character.cpp.s
.PHONY : Character.cpp.s

Enemy.o: Enemy.cpp.o

.PHONY : Enemy.o

# target to build an object file
Enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Enemy.cpp.o
.PHONY : Enemy.cpp.o

Enemy.i: Enemy.cpp.i

.PHONY : Enemy.i

# target to preprocess a source file
Enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Enemy.cpp.i
.PHONY : Enemy.cpp.i

Enemy.s: Enemy.cpp.s

.PHONY : Enemy.s

# target to generate assembly for a file
Enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Enemy.cpp.s
.PHONY : Enemy.cpp.s

Game.o: Game.cpp.o

.PHONY : Game.o

# target to build an object file
Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Game.cpp.o
.PHONY : Game.cpp.o

Game.i: Game.cpp.i

.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s

.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Game.cpp.s
.PHONY : Game.cpp.s

GameOverState.o: GameOverState.cpp.o

.PHONY : GameOverState.o

# target to build an object file
GameOverState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/GameOverState.cpp.o
.PHONY : GameOverState.cpp.o

GameOverState.i: GameOverState.cpp.i

.PHONY : GameOverState.i

# target to preprocess a source file
GameOverState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/GameOverState.cpp.i
.PHONY : GameOverState.cpp.i

GameOverState.s: GameOverState.cpp.s

.PHONY : GameOverState.s

# target to generate assembly for a file
GameOverState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/GameOverState.cpp.s
.PHONY : GameOverState.cpp.s

LeaderboardState.o: LeaderboardState.cpp.o

.PHONY : LeaderboardState.o

# target to build an object file
LeaderboardState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/LeaderboardState.cpp.o
.PHONY : LeaderboardState.cpp.o

LeaderboardState.i: LeaderboardState.cpp.i

.PHONY : LeaderboardState.i

# target to preprocess a source file
LeaderboardState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/LeaderboardState.cpp.i
.PHONY : LeaderboardState.cpp.i

LeaderboardState.s: LeaderboardState.cpp.s

.PHONY : LeaderboardState.s

# target to generate assembly for a file
LeaderboardState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/LeaderboardState.cpp.s
.PHONY : LeaderboardState.cpp.s

Leaf.o: Leaf.cpp.o

.PHONY : Leaf.o

# target to build an object file
Leaf.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Leaf.cpp.o
.PHONY : Leaf.cpp.o

Leaf.i: Leaf.cpp.i

.PHONY : Leaf.i

# target to preprocess a source file
Leaf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Leaf.cpp.i
.PHONY : Leaf.cpp.i

Leaf.s: Leaf.cpp.s

.PHONY : Leaf.s

# target to generate assembly for a file
Leaf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Leaf.cpp.s
.PHONY : Leaf.cpp.s

MenuState.o: MenuState.cpp.o

.PHONY : MenuState.o

# target to build an object file
MenuState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/MenuState.cpp.o
.PHONY : MenuState.cpp.o

MenuState.i: MenuState.cpp.i

.PHONY : MenuState.i

# target to preprocess a source file
MenuState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/MenuState.cpp.i
.PHONY : MenuState.cpp.i

MenuState.s: MenuState.cpp.s

.PHONY : MenuState.s

# target to generate assembly for a file
MenuState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/MenuState.cpp.s
.PHONY : MenuState.cpp.s

Object.o: Object.cpp.o

.PHONY : Object.o

# target to build an object file
Object.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Object.cpp.o
.PHONY : Object.cpp.o

Object.i: Object.cpp.i

.PHONY : Object.i

# target to preprocess a source file
Object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Object.cpp.i
.PHONY : Object.cpp.i

Object.s: Object.cpp.s

.PHONY : Object.s

# target to generate assembly for a file
Object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Object.cpp.s
.PHONY : Object.cpp.s

PlayState.o: PlayState.cpp.o

.PHONY : PlayState.o

# target to build an object file
PlayState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/PlayState.cpp.o
.PHONY : PlayState.cpp.o

PlayState.i: PlayState.cpp.i

.PHONY : PlayState.i

# target to preprocess a source file
PlayState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/PlayState.cpp.i
.PHONY : PlayState.cpp.i

PlayState.s: PlayState.cpp.s

.PHONY : PlayState.s

# target to generate assembly for a file
PlayState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/PlayState.cpp.s
.PHONY : PlayState.cpp.s

Player.o: Player.cpp.o

.PHONY : Player.o

# target to build an object file
Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Player.cpp.o
.PHONY : Player.cpp.o

Player.i: Player.cpp.i

.PHONY : Player.i

# target to preprocess a source file
Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Player.cpp.i
.PHONY : Player.cpp.i

Player.s: Player.cpp.s

.PHONY : Player.s

# target to generate assembly for a file
Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Player.cpp.s
.PHONY : Player.cpp.s

Shot.o: Shot.cpp.o

.PHONY : Shot.o

# target to build an object file
Shot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Shot.cpp.o
.PHONY : Shot.cpp.o

Shot.i: Shot.cpp.i

.PHONY : Shot.i

# target to preprocess a source file
Shot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Shot.cpp.i
.PHONY : Shot.cpp.i

Shot.s: Shot.cpp.s

.PHONY : Shot.s

# target to generate assembly for a file
Shot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Shot.cpp.s
.PHONY : Shot.cpp.s

Spider.o: Spider.cpp.o

.PHONY : Spider.o

# target to build an object file
Spider.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Spider.cpp.o
.PHONY : Spider.cpp.o

Spider.i: Spider.cpp.i

.PHONY : Spider.i

# target to preprocess a source file
Spider.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Spider.cpp.i
.PHONY : Spider.cpp.i

Spider.s: Spider.cpp.s

.PHONY : Spider.s

# target to generate assembly for a file
Spider.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Spider.cpp.s
.PHONY : Spider.cpp.s

SpiderSwarm.o: SpiderSwarm.cpp.o

.PHONY : SpiderSwarm.o

# target to build an object file
SpiderSwarm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/SpiderSwarm.cpp.o
.PHONY : SpiderSwarm.cpp.o

SpiderSwarm.i: SpiderSwarm.cpp.i

.PHONY : SpiderSwarm.i

# target to preprocess a source file
SpiderSwarm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/SpiderSwarm.cpp.i
.PHONY : SpiderSwarm.cpp.i

SpiderSwarm.s: SpiderSwarm.cpp.s

.PHONY : SpiderSwarm.s

# target to generate assembly for a file
SpiderSwarm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/SpiderSwarm.cpp.s
.PHONY : SpiderSwarm.cpp.s

State.o: State.cpp.o

.PHONY : State.o

# target to build an object file
State.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/State.cpp.o
.PHONY : State.cpp.o

State.i: State.cpp.i

.PHONY : State.i

# target to preprocess a source file
State.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/State.cpp.i
.PHONY : State.cpp.i

State.s: State.cpp.s

.PHONY : State.s

# target to generate assembly for a file
State.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/State.cpp.s
.PHONY : State.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... game"
	@echo "... Ant.o"
	@echo "... Ant.i"
	@echo "... Ant.s"
	@echo "... AntSwarm.o"
	@echo "... AntSwarm.i"
	@echo "... AntSwarm.s"
	@echo "... Character.o"
	@echo "... Character.i"
	@echo "... Character.s"
	@echo "... Enemy.o"
	@echo "... Enemy.i"
	@echo "... Enemy.s"
	@echo "... Game.o"
	@echo "... Game.i"
	@echo "... Game.s"
	@echo "... GameOverState.o"
	@echo "... GameOverState.i"
	@echo "... GameOverState.s"
	@echo "... LeaderboardState.o"
	@echo "... LeaderboardState.i"
	@echo "... LeaderboardState.s"
	@echo "... Leaf.o"
	@echo "... Leaf.i"
	@echo "... Leaf.s"
	@echo "... MenuState.o"
	@echo "... MenuState.i"
	@echo "... MenuState.s"
	@echo "... Object.o"
	@echo "... Object.i"
	@echo "... Object.s"
	@echo "... PlayState.o"
	@echo "... PlayState.i"
	@echo "... PlayState.s"
	@echo "... Player.o"
	@echo "... Player.i"
	@echo "... Player.s"
	@echo "... Shot.o"
	@echo "... Shot.i"
	@echo "... Shot.s"
	@echo "... Spider.o"
	@echo "... Spider.i"
	@echo "... Spider.s"
	@echo "... SpiderSwarm.o"
	@echo "... SpiderSwarm.i"
	@echo "... SpiderSwarm.s"
	@echo "... State.o"
	@echo "... State.i"
	@echo "... State.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

